### ISSUE TITLE
IE11: _oktaAuth.token.parseFromUrl() throws TypeError: Object doesn't support this action exception causing an authentication failure

### ISSUE THREAD

**Issue by MaxMTruefit** [okta/okta-auth-js#208]
I'm receiving an exception when using the @okta/okta-react package within IE11.

The symptom initially was the presence of a plain white screen that displays "TypeError: Object doesn't support this action" when the /implicit/callback component attempts to call `this.props.auth.handleAuthentication()`. Unfortunately, it didn't tell me much, other than it's likely using a feature unsupported within IE11.

I dug a little and discovered it was specifically failing on the first line of the `handleAuthentication` function within the `Auth.js` component here: `let tokens = await this._oktaAuth.token.parseFromUrl();`

Further investigation revealed it was failing on `nativeHistory.replaceState(null, nativeDoc.title, nativeLoc.pathname + nativeLoc.search);`.
(https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L543)

The full exception is:
`"TypeError: Object doesn't support this action\n   
at history[method] (http://localhost:3000/static/js/0.chunk.js:180877:5)\n   
at removeHash (http://localhost:3000/static/js/0.chunk.js:56946:5)\n   
at Anonymous function (http://localhost:3000/static/js/0.chunk.js:56983:7)\n   
at _fulfilled (http://localhost:3000/static/js/0.chunk.js:140578:9)\n   
at Anonymous function (http://localhost:3000/static/js/0.chunk.js:140609:9)\n   
at promise.promiseDispatch (http://localhost:3000/static/js/0.chunk.js:140539:9)\n   
at Anonymous function (http://localhost:3000/static/js/0.chunk.js:140603:7)\n   
at runSingle (http://localhost:3000/static/js/0.chunk.js:139859:9)\n   
at flush (http://localhost:3000/static/js/0.chunk.js:139845:9)"`

I'm still researching what's going on, I suspect I'm missing a polyfill that's required for the okta components to work as expected. At the moment, I'm using the following polyfills:
`import 'babel-polyfill/dist/polyfill';
import 'react-app-polyfill/ie11';`

Are you aware of any polyfill specific dependencies I will need to add in order to get past this issue?

**Comment by MaxMTruefit** [comment]
Further digging revealed the issue was related to a missing polyfill for `CustomEvent`.

If anyone else encounters this issue, add the following polyfill to your project:

```
(function () {

  if (typeof window.CustomEvent === 'function') return false;

  function CustomEvent(event, params) {
    params = params || { bubbles: false, cancelable: false, detail: null };
    var evt = document.createEvent('CustomEvent');
    evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail);
    return evt;
  }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
  window.Event = CustomEvent;
})();
```

You can find documentation on the polyfill here:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by swiftone** [comment]
INFO: Investigate updating eslint to explicitly list global variables rather than assuming `browser: true`

**Comment by robertjd** [comment]
Should we be adding the CustomEvent polyfill to the widget bundle?

**Comment by MaxMTruefit** [comment]
I would recommend it, CustomEvent is a dependency within your @okta/okta-react package.

Without it, the current state of the library leaves IE unsupported. (Without manually adding the polyfill)
