### ISSUE TITLE
tokenManager: { storage: 'sessionStorage' } returns error 

### ISSUE THREAD

**Issue by Anna-Cantrell** [okta/okta-auth-js#890]
I've updated to version 5.2.3 and found that I get an error when I try to set the storage option in tokenManager in the oktaAuth config object.

```
const config: OktaAuthOptions = {
  ...
  tokenManager: {
    storage: 'sessionStorage'
  }
};
const oktaAuth = new OktaAuth(config);
```
This, as well as `cookie` and `localStorage` give me this error. \<...edited for privacy\>
```
AuthSdkError: Unrecognized storage option: localStorage
    at ServerStorage.getStorageByType (<...>/node_modules/@okta/okta-auth-js/cjs/server/serverStorage.js:85:15)
    at StorageManager.getStorage (<...>/node_modules/@okta/okta-auth-js/cjs/StorageManager.js:78:29)
    at StorageManager.getTokenStorage (<...>/node_modules/@okta/okta-auth-js/cjs/StorageManager.js:155:26)
    at new TokenManager (<...>/node_modules/@okta/okta-auth-js/cjs/TokenManager.js:95:39)
    at new OktaAuth (<...>/node_modules/@okta/okta-auth-js/cjs/OktaAuth.js:196:25)
    at eval (webpack-internal:///./<...>:39:18)
    at Object../<...>.tsx (<...>/.next/server/pages/_app.js:52:1)
    at __webpack_require__ (<...>/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///<...>.tsx:12:75)
    at Object..<...> (<...>/.next/server/pages/_app.js:63:1) {
  errorCode: 'INTERNAL',
  errorSummary: 'Unrecognized storage option: localStorage',
  errorLink: 'INTERNAL',
  errorId: 'INTERNAL',
  errorCauses: []
}
```

Note sure if this is a bug in the code or an error in the documentation

**Comment by shuowu** [comment]
@Anna-Cantrell 
>     at ServerStorage.getStorageByType (<...>/node_modules/@okta/okta-auth-js/cjs/server/serverStorage.js:85:15)

Looks like you are using the CommonJS (cjs) bundle which should only work for node env. Can you share your app's setup? Then we can suggest the proper storage option for your use case.

**Comment by Anna-Cantrell** [comment]
Current doing testing on a static generated next.js app.
This is the config file:
```
const oktaAuthOptions: OktaAuthOptions = {
  clientId: "<...>",
  issuer: "<...>",
  redirectUri: "/okta/callback",
  postLogoutRedirectUri: "/loggedOut",
  scopes: ["openid", "oneid", "profile", "email"],
  pkce: true,
  cookies: {
    secure: true
  },
  storageManager: {
    token: {
      storageTypes: ["sessionStorage"]
    }
  }
};
```

**Comment by Anna-Cantrell** [comment]
I'll note that storageType within storageManager also threw an error
```
storageManager: {
  token: {
    storageType: "sessionStorage"
  }
}
```

**Comment by CharlieGreenman** [comment]
I was able to get around by creating a custom in memory storage solution: 

```
class CustomStorageProvider implements SimpleStorage {
      private storage: { [key: string]: string } = {};
    
      getItem(key: string): string | null {
        return this.storage[key] || null;
      }
    
      setItem(key: string, value: string): void {
        this.storage[key] = value;
      }
    
      removeItem(key: string): void {
        delete this.storage[key];
      }
    }
    ```
    
    and then adding to auth via 
    
    ```
    tokenManager: {
        storage: new CustomStorageProvider(),
     ```
     
     Note this will be in memory. So if this solution is followed, any existing apis that use session storage directly will break
