### ISSUE TITLE
Read Only Cookie Support in Server Side Rendering

### ISSUE THREAD

**Issue by jpspringall** [okta/okta-auth-js#939]
Hi,

I think this also relates to #890 

I previously created an issue #592 explaining the use of cookies within in server side rendering, though the actual issue raised was in relation to session cookies.

Basically cookie storage is used in server side rendering in 'readonly' mode, by reading the http headers. 

As a workaround for cookie session support in 4.x we created a custom provider.

As my PR went in with 5.x, we have switched back to the builtin cookie storage option.

However this results in the following error:

	[okta-auth-sdk] WARN: Memory storage can only support simple single user use case on server side, please provide custom storageProvider or storageKey if advanced scenarios need to be supported.
	AuthSdkError: Unrecognized storage option: cookie
		at ServerStorage.getStorageByType (server.bundle.js:367500:15)
		at StorageManager.getStorage (server.bundle.js:366665:29)
		at StorageManager.getTokenStorage (server.bundle.js:366742:24)
		at new TokenManager (server.bundle.js:365548:39)
		at new OktaAuth (server.bundle.js:330239:25)
		at new AuthenticationService (server.bundle.js:329018:27)
		at _createClass (server.bundle.js:21125:20)
		at _createProviderInstance (server.bundle.js:21095:26)
		at initNgModule (server.bundle.js:21028:32)
		at new NgModuleRef_ (server.bundle.js:21737:9) {
	  name: 'AuthSdkError',
	  errorCode: 'INTERNAL',
	  errorSummary: 'Unrecognized storage option: cookie',
	  errorLink: 'INTERNAL',
	  errorId: 'INTERNAL',
	  errorCauses: []

This caused by the following in serverStorage.ts

	getStorageByType(storageType: StorageType): SimpleStorage {
		let storageProvider = null;
		switch (storageType) {
		  case 'memory':
			storageProvider = this.getStorage();
			break;
		  default:
			throw new AuthSdkError(`Unrecognized storage option: ${storageType}`);
			break;
		}
		return storageProvider;
	}

So if Server Side Rendering is used, then the only supported storage type is memory.
However it is possible to bypasses this check in in StorageManager.ts by setting the storage type to an object

	getStorage(options: StorageOptions): SimpleStorage {
		options = Object.assign({}, this.cookieOptions, options); // set defaults
               //Short circuit if object provided
		if (options.storageProvider) {
		  return options.storageProvider;
		}
		....
		if (!storageType) {
		  storageType = this.storageUtil.findStorageType(storageTypes);
		}
		return this.storageUtil.getStorageByType(storageType, options);
	}

So a work around for this, and this may help Anna is to do the following:

	if (isClientSideRendering)
	{
		 tokenManager: {
			storage: 'cookie'
		},
		cookies: { sessionCookie: true }
	}
	else
	{
		tokenManager: {
			storage: {}
		},
	}

1. Set the storage to an object if server side rendering 
2. This means that the cookie header can be read if required
3. Set the storage to an cookie if client side rendering

The above will obviously error if you attempt to access to storage while server side rendering

So my ask is would be possible to update the serverStorage.ts to be like:

	getStorageByType(storageType: StorageType): SimpleStorage {
		let storageProvider = null;
		switch (storageType) {
			case 'memory':
				storageProvider = this.getMemoryStorage();
				break;
			case 'cookie':
				storageProvider = this.getCookieStorage();
				break;			
			default:
				throw new AuthSdkError(`Unrecognized storage option: ${storageType}`);
				break;
		}
		return storageProvider;
	}

	getCookieStorage(): SimpleStorage {
		return 	{
			getItem: (key: string) => {
				throw new AuthSdkError('Usage of cookie storage from a server is not supported, meaningful explanation');
			},
			setItem: (key: string, value: any) {
				throw new AuthSdkError('Usage of cookie storage from a server is not supported, meaningful explanation');
			},
			removeItem: (key: string) {
				throw new AuthSdkError('Usage of cookie storage from a server is not supported, meaningful explanation');
			}
		};
	}	

I'm happy to create the PR, but I wanted to get an opinion before doing the work

Thanks

James

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: OKTA-429397
