### ISSUE TITLE
Fingerprint doesn't seem to be working in v1.13

### ISSUE THREAD

**Issue by andrantis-ub** [okta/okta-auth-js#94]
Navigated to http://outstanding-auth.surge.sh/
22:06:50.522 (index):58 fingerprint
22:06:52.037 (index):65 n {name: "AuthSdkError", message: "Unable to parse iframe response", errorCode: "INTERNAL", errorSummary: "Unable to parse iframe response", errorLink: "INTERNAL", …}errorCauses: []errorCode: "INTERNAL"errorId: "INTERNAL"errorLink: "INTERNAL"errorSummary: "**Unable to parse iframe response"message**: "Unable to parse iframe response"name: "AuthSdkError"__proto__: Error
    at Object.<anonymous> (http://outstanding-auth.surge.sh/okta-auth-js.min.js:44:27276)
    at t (http://outstanding-auth.surge.sh/okta-auth-js.min.js:13:326)
    at Object.<anonymous> (http://outstanding-auth.surge.sh/okta-auth-js.min.js:44:27043)
    at t (http://outstanding-auth.surge.sh/okta-auth-js.min.js:13:326)
    at Object.<anonymous> (http://outstanding-auth.surge.sh/okta-auth-js.min.js:44:25950)
    at t (http://outstanding-auth.surge.sh/okta-auth-js.min.js:13:326)
    at Object.<anonymous> (http://outstanding-auth.surge.sh/okta-auth-js.min.js:44:22559)
    at t (http://outstanding-auth.surge.sh/okta-auth-js.min.js:13:326)
    at Object.<anonymous> (http://outstanding-auth.surge.sh/okta-auth-js.min.js:44:20873)
    at t (http://outstanding-auth.surge.sh/okta-auth-js.min.js:13:326)
22:06:52.040 VM7566:1 XHR failed loading: POST "https://dev-217923.oktapreview.com/api/v1/internal/device/nonce".

**Comment by jmelberg-okta** [comment]
Hey @andrantis-ub - we pushed an update to our fingerprinting logic recently. Can you see if the issue still remains with `@okta/okta-auth-js@1.16.0`?

If it does, please provide us with reproduction steps to ensure we can properly investigate. Thanks!

**Comment by andrantis-ub** [comment]
Hey @jackychen-okta I think the issue has being solved. Thanks!
