### ISSUE TITLE
Uncaught exception thrown when cookies disabled

### ISSUE THREAD

**Issue by bpedersen** [okta/okta-auth-js#952]
This library throws an uncaught exception when the browser has cookies disabled. It appears that setOriginialUri tries to use sessionStorage without checking if it is available first. This is affecting the okta-react library and won't let you gracefully handle the exception.

`Uncaught (in promise) DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at Object.getSessionStorage (http://localhost:3000/static/js/vendors~main.chunk.js:53863:9)
    at t.value (http://localhost:3000/static/js/vendors~main.chunk.js:58240:14)
    at _callee$ (http://localhost:3000/static/js/vendors~main.chunk.js:58611:26)
    at tryCatch (http://localhost:3000/static/js/vendors~main.chunk.js:187601:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/vendors~main.chunk.js:187815:22)
    at Generator.next (http://localhost:3000/static/js/vendors~main.chunk.js:187653:21)
    at asyncGeneratorStep (http://localhost:3000/static/js/vendors~main.chunk.js:11967:24)
    at _next (http://localhost:3000/static/js/vendors~main.chunk.js:11989:9)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11996:7
    at new Promise (<anonymous>)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11985:12
    at handleLogin (http://localhost:3000/static/js/vendors~main.chunk.js:58639:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:58658:7
    at commitHookEffectListMount (http://localhost:3000/static/js/vendors~main.chunk.js:164735:30)
    at commitPassiveHookEffects (http://localhost:3000/static/js/vendors~main.chunk.js:164772:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:145317:18)
    at HTMLUnknownElement.__trace__ (http://localhost:3000/static/js/vendors~main.chunk.js:15416:32)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:145366:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:145419:35)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/vendors~main.chunk.js:167836:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:190474:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:156204:14)
    at flushPassiveEffects (http://localhost:3000/static/js/vendors~main.chunk.js:167804:16)
    at http://localhost:3000/static/js/vendors~main.chunk.js:167683:15
    at workLoop (http://localhost:3000/static/js/vendors~main.chunk.js:190418:38)
    at flushWork (http://localhost:3000/static/js/vendors~main.chunk.js:190374:20)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/static/js/vendors~main.chunk.js:189978:31)`

PROPOSED FIX:
Change the following function to check for sessionStorage before writing to it. https://github.com/okta/okta-auth-js/blob/7cb9599fbf18b53f2e3a90c4e82bb65770d41887/lib/OktaAuth.ts#L561

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for reporting this!

Our team will review this issue and get back with an answer.

**Comment by shuowu** [comment]
Internal Ref: OKTA-431793

**Comment by shuowu** [comment]
@bpedersen The fix actually happens in okta-react, we added `errorComponent` props to the `SecureRoute`, so any error from the internal process can be caught and handled gracefully from UI.

The fix is available in [okta-react v6.3](https://github.com/okta/okta-react/releases/tag/okta-react-6.3.0)
